name: "\U0001F680 Feature request"
description: Suggest an idea or enhancement for the solution accelerator
title: "[Feature]: "
labels: [enhancement]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the solution does this enhancement relate to?
      options:
        - Console Application (CLI)
        - Core Library
        - Infrastructure (Bicep/infra)
        - Documentation
        - GitHub Actions / CI/CD
        - Testing
        - Dependency Management
        - Code Quality / Refactoring
        - Other
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this feature solve? Why is it needed?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
