//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenAIDBExplorer.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenAIDBExplorer.Core.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding stored procedure [{schemaName}].[{storedProcedureName}] to the semantic model.
        /// </summary>
        internal static string AddingStoredProcedureToSemanticModel {
            get {
                return ResourceManager.GetString("AddingStoredProcedureToSemanticModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding table [{schemaName}].[{tableName}] to the semantic model.
        /// </summary>
        internal static string AddingTableToSemanticModel {
            get {
                return ResourceManager.GetString("AddingTableToSemanticModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding view [{schemaName}].[{viewName}] to the semantic model.
        /// </summary>
        internal static string AddingViewToSemanticModel {
            get {
                return ResourceManager.GetString("AddingViewToSemanticModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to SQL database.
        /// </summary>
        internal static string ConnectingSQLDatabase {
            get {
                return ResourceManager.GetString("ConnectingSQLDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to SQL database opened successfully.
        /// </summary>
        internal static string ConnectSQLSuccessful {
            get {
                return ResourceManager.GetString("ConnectSQLSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection state &apos;{ConnectionState}&apos;.
        /// </summary>
        internal static string DatabaseConnectionState {
            get {
                return ResourceManager.GetString("DatabaseConnectionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing SQL query &apos;{query}&apos;.
        /// </summary>
        internal static string ExecutingSQLQuery {
            get {
                return ResourceManager.GetString("ExecutingSQLQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting semantic model for database &apos;{DatabaseName}&apos;.
        /// </summary>
        internal static string ExtractingModelForDatabase {
            get {
                return ResourceManager.GetString("ExtractingModelForDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed generation of semantic description for stored procedure [{schemaName}].[{storedProcedureName}].
        /// </summary>
        internal static string GeneratedSemanticDescriptionForStoredProcedure {
            get {
                return ResourceManager.GetString("GeneratedSemanticDescriptionForStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed generation of semantic description for table [{schemaName}].[{tableName}].
        /// </summary>
        internal static string GeneratedSemanticDescriptionForTable {
            get {
                return ResourceManager.GetString("GeneratedSemanticDescriptionForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed generation of semantic description for view [{schemaName}].[{viewName}].
        /// </summary>
        internal static string GeneratedSemanticDescriptionForView {
            get {
                return ResourceManager.GetString("GeneratedSemanticDescriptionForView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating semantic description for stored procedure [{schemaName}].[{storedProcedureName}].
        /// </summary>
        internal static string GenerateSemanticDescriptionForStoredProcedure {
            get {
                return ResourceManager.GetString("GenerateSemanticDescriptionForStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating semantic description for table [{schemaName}].[{tableName}].
        /// </summary>
        internal static string GenerateSemanticDescriptionForTable {
            get {
                return ResourceManager.GetString("GenerateSemanticDescriptionForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating semantic description for view [{schemaName}].[{viewName}].
        /// </summary>
        internal static string GenerateSemanticDescriptionForView {
            get {
                return ResourceManager.GetString("GenerateSemanticDescriptionForView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting list of tables from view definition for [{schemaName}].[{viewName}].
        /// </summary>
        internal static string GetTableListFromViewDefinition {
            get {
                return ResourceManager.GetString("GetTableListFromViewDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed getting list of {TableCount} tables from view definition for [{schemaName}].[{viewName}].
        /// </summary>
        internal static string GotTableListFromViewDefinition {
            get {
                return ResourceManager.GetString("GotTableListFromViewDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic model loaded successfully for database &apos;{DatabaseName}&apos;.
        /// </summary>
        internal static string LoadedSemanticModelForDatabase {
            get {
                return ResourceManager.GetString("LoadedSemanticModelForDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading semantic model from &apos;{ModelPath}&apos;.
        /// </summary>
        internal static string LoadingSemanticModel {
            get {
                return ResourceManager.GetString("LoadingSemanticModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings validation completed.
        /// </summary>
        internal static string ProjectSettingsValidationCompleted {
            get {
                return ResourceManager.GetString("ProjectSettingsValidationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings validation started.
        /// </summary>
        internal static string ProjectSettingsValidationStarted {
            get {
                return ResourceManager.GetString("ProjectSettingsValidationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project settings &apos;{Section}&apos; validated successfully..
        /// </summary>
        internal static string ProjectSettingsValidationSuccessful {
            get {
                return ResourceManager.GetString("ProjectSettingsValidationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table [{schemaName}].[{tableName}] used by the view does not have a semantic description..
        /// </summary>
        internal static string TableMissingSemanticDescription {
            get {
                return ResourceManager.GetString("TableMissingSemanticDescription", resourceCulture);
            }
        }
    }
}
