//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenAIDBExplorer.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenAIDBExplorer.Data.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding stored procedure {SchemaName}.{StoredProcedure} to the semantic model.
        /// </summary>
        internal static string AddingStoredProcedureToSemanticModel {
            get {
                return ResourceManager.GetString("AddingStoredProcedureToSemanticModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding table {SchemaName}.{TableName} to the semantic model.
        /// </summary>
        internal static string AddingTableToSemanticModel {
            get {
                return ResourceManager.GetString("AddingTableToSemanticModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding view {SchemaName}.{ViewName} to the semantic model.
        /// </summary>
        internal static string AddingViewToSemanticModel {
            get {
                return ResourceManager.GetString("AddingViewToSemanticModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to SQLdatabase.
        /// </summary>
        internal static string ConnectingSQLDatabase {
            get {
                return ResourceManager.GetString("ConnectingSQLDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to SQL database opened successfully.
        /// </summary>
        internal static string ConnectSQLSuccessful {
            get {
                return ResourceManager.GetString("ConnectSQLSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection state: {ConnectionState}.
        /// </summary>
        internal static string DatabaseConnectionState {
            get {
                return ResourceManager.GetString("DatabaseConnectionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing SQL query: {query}.
        /// </summary>
        internal static string ExecutingSQLQuery {
            get {
                return ResourceManager.GetString("ExecutingSQLQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting semantic model for database &apos;{Database}&apos;.
        /// </summary>
        internal static string ExtractingModelForDatabase {
            get {
                return ResourceManager.GetString("ExtractingModelForDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic model loaded successfully for database &apos;{Database}&apos;.
        /// </summary>
        internal static string LoadedSemanticModelForDatabase {
            get {
                return ResourceManager.GetString("LoadedSemanticModelForDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading semantic model from &apos;{ModelPath}&apos;.
        /// </summary>
        internal static string LoadingSemanticModel {
            get {
                return ResourceManager.GetString("LoadingSemanticModel", resourceCulture);
            }
        }
    }
}
