//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenAIDBExplorer.AI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenAIDBExplorer.AI.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed generation of semantic description for stored procedure &apos;{Schema}.{Name}&apos;.
        /// </summary>
        internal static string GeneratedSemanticDescriptionForStoredProcedure {
            get {
                return ResourceManager.GetString("GeneratedSemanticDescriptionForStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed generation of semantic description for table &apos;{Schema}.{Name}&apos;.
        /// </summary>
        internal static string GeneratedSemanticDescriptionForTable {
            get {
                return ResourceManager.GetString("GeneratedSemanticDescriptionForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed generation of semantic description for view &apos;{Schema}.{Name}&apos;.
        /// </summary>
        internal static string GeneratedSemanticDescriptionForView {
            get {
                return ResourceManager.GetString("GeneratedSemanticDescriptionForView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating semantic description for stored procedure &apos;{Schema}.{Name}&apos;.
        /// </summary>
        internal static string GenerateSemanticDescriptionForStoredProcedure {
            get {
                return ResourceManager.GetString("GenerateSemanticDescriptionForStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating semantic description for table &apos;{Schema}.{Name}&apos;.
        /// </summary>
        internal static string GenerateSemanticDescriptionForTable {
            get {
                return ResourceManager.GetString("GenerateSemanticDescriptionForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating semantic description for view &apos;{Schema}.{Name}&apos;.
        /// </summary>
        internal static string GenerateSemanticDescriptionForView {
            get {
                return ResourceManager.GetString("GenerateSemanticDescriptionForView", resourceCulture);
            }
        }
    }
}
