name: build-applications

on:
  workflow_call:
    inputs:
      BUILD_VERSION:
        description: 'The version to assign to the applications'
        type: string
        default: '0.0.0'
      BUILD_CONFIGURATION:
        description: 'The build configuration to use (e.g., Debug or Release)'
        type: string
        default: 'Debug'

jobs:
  build-console-app:
    name: Build console app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: windows-latest
            rid: win-x64
          - os: macos-latest
            rid: osx-x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: Publish Solution
        run: dotnet publish ./src/GenAIDBExplorer/GenAIDBExplorer.sln -c ${{ inputs.BUILD_CONFIGURATION }} -r ${{ matrix.rid }} -p:Version=${{ inputs.BUILD_VERSION }} --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TargetName=gaidbexp -o ./publish/${{ matrix.rid }}-${{ inputs.BUILD_VERSION }}

      - name: Upload Artifact to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: gaidbexp-${{ matrix.rid }}-{{ inputs.BUILD_VERSION }}
          path: ./publish/${{ matrix.rid }}-{{ inputs.BUILD_VERSION }}