name: build-applications

on:
  workflow_call:
    inputs:
      BUILD_CONFIGURATION:
        description: 'The version to assign to the client'
        type: string
        default: 'Debug'

jobs:
  build-console-app:
    name: Build console app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: Build Console App
        run: dotnet build ./src/GenAIDBExplorer/GenAIDBExplorer.Console/GenAIDBExplorer.Console.csproj -c ${{ inputs.BUILD_CONFIGURATION }}
