name: Console App Integration Tests

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "The environment to use for integration testing"
        required: true
        type: string
      RESOURCE_GROUP_NAME:
        description: "The Azure resource group name containing the SQL Server"
        required: true
        type: string
      SQL_SERVER_NAME:
        description: "The SQL Server name for database connection"
        required: true
        type: string
      AZURE_AI_FOUNDRY_ENDPOINT:
        description: "The Azure AI Foundry endpoint for AI operations"
        required: false
        type: string
      AZURE_AI_FOUNDRY_NAME:
        description: "The Azure AI Foundry resource name for endpoint construction"
        required: false
        type: string

    secrets:
      SQL_SERVER_USERNAME:
        description: "The SQL Server username for the application"
        required: true
      SQL_SERVER_PASSWORD:
        description: "The SQL Server password for the application"
        required: true
      AZURE_CLIENT_ID:
        description: "Azure service principal client ID for authentication"
        required: true
      AZURE_TENANT_ID:
        description: "Azure tenant ID for authentication"
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: "Azure subscription ID for resource access"
        required: true

jobs:
  console-app-integration-tests:
    name: Console App Integration Tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Download Console App Artifact
        uses: actions/download-artifact@v4
        with:
          name: console-app-published
          path: ./publish

      - name: Make Console App Executable
        run: chmod +x ./publish/GenAIDBExplorer.Console

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure SQL Server Firewall for GitHub Runner
        shell: bash
        run: |
          # Get the current runner's public IP address
          RUNNER_IP=$(curl -s https://ipinfo.io/ip)
          echo "GitHub Runner IP: $RUNNER_IP"

          # Use the provided resource group and SQL server names
          SQL_SERVER_NAME="${{ inputs.SQL_SERVER_NAME }}"
          RESOURCE_GROUP="${{ inputs.RESOURCE_GROUP_NAME }}"

          echo "Adding firewall rule for SQL Server: $SQL_SERVER_NAME"
          echo "Resource Group: $RESOURCE_GROUP"
          echo "Runner IP: $RUNNER_IP"

          # Add firewall rule for the GitHub runner IP
          az sql server firewall-rule create \
            --resource-group "$RESOURCE_GROUP" \
            --server "$SQL_SERVER_NAME" \
            --name "GitHubRunner-${{ github.run_id }}" \
            --start-ip-address "$RUNNER_IP" \
            --end-ip-address "$RUNNER_IP"

          echo "Firewall rule created successfully"

      - name: Enable Azure AI Foundry Public Access for Integration Tests
        shell: bash
        run: |
          # Extract environment suffix from SQL server name for AI Foundry service name
          SQL_SERVER_NAME="${{ inputs.SQL_SERVER_NAME }}"
          RESOURCE_GROUP="${{ inputs.RESOURCE_GROUP_NAME }}"
          
          # Try to construct AI Foundry service name from SQL server pattern
          if [[ "$SQL_SERVER_NAME" =~ ^sql-(.+)$ ]]; then
            ENV_SUFFIX="${BASH_REMATCH[1]}"
            AI_FOUNDRY_NAME="aif-${ENV_SUFFIX}"
            echo "Constructed AI Foundry service name: $AI_FOUNDRY_NAME"
            
            # Get the resource ID for the AI Foundry service
            echo "Getting resource ID for AI Foundry service: $AI_FOUNDRY_NAME"
            RESOURCE_ID=$(az cognitiveservices account show \
              --name "$AI_FOUNDRY_NAME" \
              --resource-group "$RESOURCE_GROUP" \
              --query id \
              --output tsv 2>/dev/null || echo "")
            
            if [ -n "$RESOURCE_ID" ] && [ "$RESOURCE_ID" != "" ]; then
              # Enable public network access for AI Foundry service during tests
              echo "Enabling public network access for AI Foundry service: $AI_FOUNDRY_NAME"
              az resource update \
                --ids "$RESOURCE_ID" \
                --set properties.networkAcls='{"defaultAction":"Allow"}' \
                --output none
              
              echo "Public network access enabled for AI Foundry service"
              echo "AI_FOUNDRY_NAME=$AI_FOUNDRY_NAME" >> $GITHUB_ENV
            else
              echo "Warning: Could not find AI Foundry service: $AI_FOUNDRY_NAME"
              echo "AI Foundry public access will not be modified"
            fi
          else
            echo "Warning: Could not parse SQL server name pattern to construct AI Foundry service name"
            echo "Expected format: sql-<environment-suffix>, got: $SQL_SERVER_NAME"
            echo "AI Foundry public access will not be modified"
          fi

      - name: Get Azure OpenAI API Key
        shell: bash
        run: |
          # Use the AI Foundry service name from the previous step
          if [ -n "$AI_FOUNDRY_NAME" ] && [ "$AI_FOUNDRY_NAME" != "" ]; then
            RESOURCE_GROUP="${{ inputs.RESOURCE_GROUP_NAME }}"
            
            # Get Azure OpenAI API key from Cognitive Services
            echo "Retrieving Azure OpenAI API key from AI Foundry service: $AI_FOUNDRY_NAME"
            API_KEY=$(az cognitiveservices account keys list \
              --name "$AI_FOUNDRY_NAME" \
              --resource-group "$RESOURCE_GROUP" \
              --query "key1" \
              --output tsv 2>/dev/null || echo "")
            
            if [ -n "$API_KEY" ] && [ "$API_KEY" != "" ]; then
              echo "Azure OpenAI API key retrieved successfully"
              echo "AZURE_OPENAI_API_KEY=$API_KEY" >> $GITHUB_ENV
            else
              echo "Warning: Could not retrieve Azure OpenAI API key from service: $AI_FOUNDRY_NAME"
              echo "AI-related integration tests may fail or be skipped"
            fi
          else
            echo "Warning: No AI Foundry service name available from previous step"
            echo "AI-related integration tests may fail or be skipped"
          fi

      - name: Setup PowerShell and Run Console Integration Tests
        shell: pwsh
        env:
          SQL_CONNECTION_STRING: "Server=${{ inputs.SQL_SERVER_NAME }}.database.windows.net;Database=AdventureWorksLT;User Id=${{ secrets.SQL_SERVER_USERNAME }};Password=${{ secrets.SQL_SERVER_PASSWORD }};Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          AZURE_OPENAI_ENDPOINT: ${{ inputs.AZURE_AI_FOUNDRY_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ env.AZURE_OPENAI_API_KEY }}
          CONSOLE_APP_PATH: ./publish/GenAIDBExplorer.Console
        run: |
          # Install and import Pester in the same session
          Write-Host "Installing and importing Pester module..." -ForegroundColor Yellow
          Install-Module -Name Pester -Force -Scope CurrentUser -MinimumVersion 5.7.1 -AllowClobber
          Import-Module Pester -Force -PassThru

          # Verify Pester is loaded
          $pesterVersion = Get-Module Pester | Select-Object -ExpandProperty Version
          Write-Host "Pester version loaded: $pesterVersion" -ForegroundColor Green

          # Debug environment variables
          Write-Host "=== Environment Variables Debug ===" -ForegroundColor Magenta
          Write-Host "SQL_CONNECTION_STRING: $($env:SQL_CONNECTION_STRING.Length) characters" -ForegroundColor Yellow
          Write-Host "AZURE_OPENAI_ENDPOINT: '$env:AZURE_OPENAI_ENDPOINT'" -ForegroundColor Yellow
          Write-Host "AZURE_OPENAI_API_KEY: $($env:AZURE_OPENAI_API_KEY.Length) characters (masked)" -ForegroundColor Yellow
          Write-Host "Input AZURE_AI_FOUNDRY_ENDPOINT: '${{ inputs.AZURE_AI_FOUNDRY_ENDPOINT }}'" -ForegroundColor Yellow
          Write-Host "Input AZURE_AI_FOUNDRY_NAME: '${{ inputs.AZURE_AI_FOUNDRY_NAME }}'" -ForegroundColor Yellow

          # Construct OpenAI endpoint if not provided but name is available
          if ([string]::IsNullOrEmpty($env:AZURE_OPENAI_ENDPOINT) -and -not [string]::IsNullOrEmpty('${{ inputs.AZURE_AI_FOUNDRY_NAME }}')) {
            $constructedEndpoint = "https://${{ inputs.AZURE_AI_FOUNDRY_NAME }}.cognitiveservices.azure.com/"
            Write-Host "Constructing OpenAI endpoint from AI Foundry name: $constructedEndpoint" -ForegroundColor Cyan
            $env:AZURE_OPENAI_ENDPOINT = $constructedEndpoint
          }

          # If we still don't have an endpoint and we know the SQL server name, try to construct from that pattern
          if ([string]::IsNullOrEmpty($env:AZURE_OPENAI_ENDPOINT) -and -not [string]::IsNullOrEmpty('${{ inputs.SQL_SERVER_NAME }}')) {
            # Extract the environment suffix from SQL server name (e.g., sql-gaidbexp-16461932142 -> gaidbexp-16461932142)
            $sqlServerName = '${{ inputs.SQL_SERVER_NAME }}'
            if ($sqlServerName -match '^sql-(.+)$') {
              $envSuffix = $matches[1]
              $constructedEndpoint = "https://$envSuffix.cognitiveservices.azure.com/"
              Write-Host "Constructing OpenAI endpoint from SQL server pattern: $constructedEndpoint" -ForegroundColor Yellow
              $env:AZURE_OPENAI_ENDPOINT = $constructedEndpoint
            }
          }

          # Check if endpoint and API key are available for AI tests
          if ([string]::IsNullOrEmpty($env:AZURE_OPENAI_ENDPOINT) -or [string]::IsNullOrEmpty($env:AZURE_OPENAI_API_KEY)) {
            Write-Warning "Azure AI Foundry endpoint or API key not available. AI-related integration tests will be skipped or may fail gracefully."
            Write-Host "This is expected behavior when AI services are not deployed or configured." -ForegroundColor Yellow
            Write-Host "To enable AI tests, ensure AZURE_AI_FOUNDRY_ENDPOINT is passed correctly from infrastructure provisioning." -ForegroundColor Yellow
            Write-Host "Check the 'Get Output Endpoints' step in provision-infrastructure workflow for Azure CLI endpoint retrieval." -ForegroundColor Yellow
            if ([string]::IsNullOrEmpty($env:AZURE_OPENAI_API_KEY)) {
              Write-Host "API key was not retrieved - check that the AI Foundry service exists and has the expected naming pattern." -ForegroundColor Yellow
            }
          } else {
            Write-Host "Azure AI services configured with endpoint and API key. AI integration tests will run." -ForegroundColor Green
            Write-Host "Endpoint format: $($env:AZURE_OPENAI_ENDPOINT)" -ForegroundColor Cyan

            # Validate endpoint format
            if ($env:AZURE_OPENAI_ENDPOINT -match 'https://.*\.cognitiveservices\.azure\.com/?$') {
              Write-Host "✅ Valid Azure Cognitive Services endpoint format detected" -ForegroundColor Green
              Write-Host "   This endpoint supports OpenAI API calls at /openai/* paths" -ForegroundColor Green
            } elseif ($env:AZURE_OPENAI_ENDPOINT -match 'https://.*\.openai\.azure\.com/?$') {
              Write-Host "✅ Valid Azure OpenAI endpoint format detected" -ForegroundColor Green
            } else {
              Write-Warning "⚠️  Unexpected endpoint format - tests may still work but verify configuration"
              Write-Host "   Expected: https://<name>.cognitiveservices.azure.com/ or https://<name>.openai.azure.com/" -ForegroundColor Yellow
            }
          }
          Write-Host "===================================" -ForegroundColor Magenta

          # Create test results directory
          New-Item -ItemType Directory -Path "./test-results" -Force | Out-Null

          # Configure Pester
          $config = New-PesterConfiguration
          $config.Run.Path = './src/Tests/Integration/Console.Integration.Tests.ps1'
          $config.Output.Verbosity = 'Detailed'
          $config.TestResult.Enabled = $true
          $config.TestResult.OutputFormat = 'NUnitXml'
          $config.TestResult.OutputPath = './test-results/integration-tests.xml'
          $config.CodeCoverage.Enabled = $false
          $config.Should.ErrorAction = 'Continue'

          try {
            Write-Host "Starting console integration tests..." -ForegroundColor Green
            Write-Host "SQL Server: ${{ inputs.SQL_SERVER_NAME }}" -ForegroundColor Yellow
            Write-Host "Azure AI Foundry Endpoint: ${{ inputs.AZURE_AI_FOUNDRY_ENDPOINT }}" -ForegroundColor Yellow
            Invoke-Pester -Configuration $config
            Write-Host "Integration tests completed" -ForegroundColor Green
          } catch {
            Write-Error "Integration tests failed: $($_.Exception.Message)"
            throw
          }

      - name: Publish Integration Test Results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Console Integration Test Results
          path: './test-results/integration-tests.xml'
          reporter: java-junit

      - name: Upload Integration Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: console-integration-test-results
          path: |
            ./test-results/
            ./temp-workspaces/
          retention-days: 7

      - name: Disable Azure AI Foundry Public Access After Tests
        if: always()
        shell: bash
        run: |
          # Disable public network access for AI Foundry service after tests
          if [ -n "$AI_FOUNDRY_NAME" ] && [ "$AI_FOUNDRY_NAME" != "" ]; then
            RESOURCE_GROUP="${{ inputs.RESOURCE_GROUP_NAME }}"
            
            # Get the resource ID for the AI Foundry service
            echo "Getting resource ID for AI Foundry service: $AI_FOUNDRY_NAME"
            RESOURCE_ID=$(az cognitiveservices account show \
              --name "$AI_FOUNDRY_NAME" \
              --resource-group "$RESOURCE_GROUP" \
              --query id \
              --output tsv 2>/dev/null || echo "")
            
            if [ -n "$RESOURCE_ID" ] && [ "$RESOURCE_ID" != "" ]; then
              echo "Disabling public network access for AI Foundry service: $AI_FOUNDRY_NAME"
              az resource update \
                --ids "$RESOURCE_ID" \
                --set properties.networkAcls='{"defaultAction":"Deny"}' \
                --output none || echo "Warning: Failed to disable public access for AI Foundry service"
              
              echo "Public network access disabled for AI Foundry service"
            else
              echo "Warning: Could not find AI Foundry service: $AI_FOUNDRY_NAME"
            fi
          else
            echo "No AI Foundry service name available - skipping public access cleanup"
          fi

      - name: Remove SQL Server Firewall Rule
        if: always()
        shell: bash
        run: |
          # Use the provided resource group and SQL server names
          RESOURCE_GROUP="${{ inputs.RESOURCE_GROUP_NAME }}"
          SQL_SERVER_NAME="${{ inputs.SQL_SERVER_NAME }}"

          echo "Removing firewall rule for SQL Server: $SQL_SERVER_NAME"
          echo "Resource Group: $RESOURCE_GROUP"

          # Remove the firewall rule (ignore errors if rule doesn't exist)
          az sql server firewall-rule delete \
            --resource-group "$RESOURCE_GROUP" \
            --server "$SQL_SERVER_NAME" \
            --name "GitHubRunner-${{ github.run_id }}" \
            --yes || echo "Firewall rule not found or already removed"

          echo "Firewall rule cleanup completed"
