name: continuous-integration

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  set-build-variables:
    uses: ./.github/workflows/set-build-variables.yml

  test-run-unit-tests:
    needs:
      - set-build-variables
    uses: ./.github/workflows/test-run-unit-tests.yml

  build-applications:
    needs:
      - test-run-unit-tests
    uses: ./.github/workflows/build-applications.yml
    with:
      BUILD_CONFIGURATION: Debug
    
  publish-applications:
    needs:
      - build-applications
    uses: ./.github/workflows/publish-applications.yml
    with:
      BUILD_CONFIGURATION: Debug

  build-arm-templates:
    uses: ./.github/workflows/build-arm-templates.yml