name: publish-release

on:
  workflow_call:

jobs:
  publish-console-app:
    name: Publish console app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download console Linux app artifacts
        uses: actions/download-artifact@v3
        with:
          name: gaidbexp-ubuntu-latest
          path: ./publish/ubuntu-latest

      - name: Download console Windows app artifacts
        uses: actions/download-artifact@v3
        with:
          name: gaidbexp-windows-latest
          path: ./publish/windows-latest

      - name: Download console macOS app artifacts
        uses: actions/download-artifact@v3
        with:
          name: gaidbexp-macos-latest
          path: ./publish/macos-latest

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Linux Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/ubuntu-latest
          asset_name: gaidbexp-ubuntu-latest
          asset_content_type: application/zip

      - name: Upload Release Windows Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/windows-latest
          asset_name: gaidbexp-windows-latest
          asset_content_type: application/zip

      - name: Upload Release macOS Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/macos-latest
          asset_name: gaidbexp-macos-latest
          asset_content_type: application/zip