name: set-build-variables

on:
  workflow_call:
    outputs:
      BUILD_VERSION:
        description: The build version
        value: ${{ jobs.set-build-variables.outputs.build_version }}

jobs:
  set-build-variables:
    name: Set build variables
    runs-on: windows-latest
    outputs:
      build_version: ${{ steps.calculate-build-version.outputs.build_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool --version 5.*

      - name: Calculate version with GitVersion
        id: calculate-build-version
        run: |
          $gitVersionObject = dotnet-gitversion | ConvertFrom-Json
          echo "BUILD_VERSION=$($gitVersionObject.FullSemVer)" >> $GITHUB_ENV
          echo "::set-output name=build_version::$($gitVersionObject.FullSemVer)"