name: test-run-unit-tests

on:
  workflow_call:
    inputs:
      BUILD_CONFIGURATION:
        description: 'The build configuration to use (e.g., Debug or Release)'
        type: string
        default: 'Release'

jobs:
  test-run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['GenAIDBExplorer.Console']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: Run unit tests on ${{ matrix.project }}
        run: |
          dotnet test ${{ matrix.project }}.Test.csproj --configuration ${{ inputs.BUILD_CONFIGURATION }} --logger "trx;LogFileName=${{ matrix.project }}.trx" --verbosity normal
        working-directory: ./src/GenAIDBExplorer/Tests/Unit/${{ matrix.project }}.Test/

      - name: Upload unit test results for ${{ matrix.project }}
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ matrix.project }}.Test
          path: ./src/GenAIDBExplorer/Tests/Unit/${{ matrix.project }}.Test/bin/${{ inputs.BUILD_CONFIGURATION }}/net9.0/TestResults/${{ matrix.project }}.trx

      - name: Publish unit test results for ${{ matrix.project }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ always() }}
        with:
            files: |
              ./src/GenAIDBExplorer/Tests/Unit/${{ matrix.project }}.Test/bin/${{ inputs.BUILD_CONFIGURATION }}/net9.0/TestResults/${{ matrix.project }}.trx
            check_name: Unit tests ${{ matrix.project }}.Test