name: test-run-unit-tests

on:
  workflow_call:

jobs:
  test-run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ['GenAIDBExplorer.Console']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: Run unit tests on ${{ matrix.project }}
        run: |
          dotnet test --configuration Release --logger trx --verbosity normal --results-directory "TestResults-${{ matrix.project }}"

      - name: Upload test results for ${{ matrix.project }}
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: dotnet-results-${{ matrix.project }}
          path: TestResults-${{ matrix.project }}

      - name: Publish test results for ${{ matrix.project }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ always() }}
        with:
            files: |
              ./src/GenAIDBExplorer/Tests/Unit/${{ matrix.project }}.Test/TestResults/TestResults.trx
            check_name: Unit tests ${{ matrix.project }}.Test
